language: go

go:
  - 1.7.x
  - 1.8.x

install:
  - go get github.com/stretchr/testify/assert
  - go get github.com/mattn/goveralls

script:
  - go test -v -coverprofile=cover.out -covermode=count $(go list ./... | grep -v ./examples)
  - $GOPATH/bin/goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
